class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Tandrusti',
      'directory': 'Directory',
      'medicines': 'Medicines',
      'lab_guide': 'Lab Guide',
      'reminders': 'Reminders',
      'settings': 'Settings',
      'city_filter': 'All Cities',
      'admin_upload': 'Admin: Upload Initial Data',
      'report_error': 'Report an Error',
      'language': 'Language',
      'kurdish': 'Kurdish (Sorani)',
      'english': 'English',
      'theme': 'Dark Mode',
      'working_hours': 'Working Hours:',
      'phone': 'Phone:',
      'location': 'Location:',
      'usage': 'Usage Instructions',
      'side_effects': 'Side Effects',
      'specialty': 'Specialty:',
      'get_directions': 'Get Directions',
      'empty_list': 'Empty list. Please click Upload Initial Data in Settings.',
      'add_reminder': 'Add Reminder',
      'new_reminder': 'New Pill Reminder',
      'medicine_name': 'Medicine Name',
      'pick_time': 'Pick Time',
      'cancel': 'Cancel',
      'schedule': 'Schedule',
      'save': 'Save',
      'add': '+ Add',
      'dose_hint': 'Dose',
      'no_reminders': 'No Reminders Scheduled',
      'search_medicine': 'Search by Name or Brand',
      'search_doctor': 'Search by Name or Specialty',
      'preparation': 'Preparation:',
      'what_to_expect': 'What to expect:',
      'no_tests': 'No test instructions available in the cloud.',
      'app_preferences': 'App Preferences',
      'info_support': 'Information & Support',
      'report_error_title': 'Report an Error',
      'report_error_subtitle': 'Flag incorrect clinic locations',
      'seed_starting': 'Starting Cloud Sync...',
      'seed_success': 'All data successfully sent to Google Cloud!',
      'dark_mode': 'Dark Mode',
      'dark_mode_sub': 'Toggle application theme',
      'currently': 'Currently:',
      'seed_subtitle': 'Send all data to Firebase Cloud',
      'notification_title': 'Take your Medication!',
      'notification_body': 'Friendly reminder to take',
      'scheduled_dose': 'Scheduled Dose',
      'email_subject': 'Clinic Location Error Reporting',
      'email_error': 'Could not open email app',
      'app_subtitle': 'Your Healthcare Companion in Kurdistan',
      'directory_title': 'Doctor Directory',
      'open': 'Open',
      'closed': 'Closed',
      'back': 'Back',
      'clinic_info': 'CLINIC INFORMATION',
      'address': 'Address',
      'call_btn': 'Call',
      'report_incorrect': 'Report Incorrect Info',
      'my_doctors': 'My Doctors',
      'saved': 'saved',
      'no_saved_doctors': 'Bookmark more doctors from the directory',
      'saved_doctors': 'saved doctors',
      'my_medicines': 'My Medicines',
      'no_saved_medicines': 'Bookmark more medicines from the guide',
      'medicine_guide': 'Medicine Guide',
      'scientific_brand_search': 'Scientific & brand search',
      'search_medicine_hint': 'e.g. Amoxicillin, Panadol...',
      'uses': 'Uses',
      'dosage_info': 'Dosage',
      'contraindications': 'Contraindications',
      'lab_diagnostics': 'Lab & Diagnostics',
      'prep_guides': 'Preparation guides',
      'search_tests_hint': 'Search tests...',
      'prep_steps_count': 'prep steps',
      'what_is_it': 'WHAT IS IT?',
      'prep_steps': 'PREPARATION STEPS',
      'pill_reminders': 'Pill Reminders',
      'never_miss_dose': 'Never miss a dose',
      'alarm_time_to_take': 'Time to take your medicine!',
      'alarm_took_medicine': 'I Took My Medication',
      'sponsored': 'SPONSORED',
      
      // Medicine/Test detail fallback strings
      'Medicine': 'Medicine',
      'Vitamin': 'Vitamin',
      'Supplement': 'Supplement',
      'No usage data': 'No usage data',
      'Refer to doctor': 'Refer to doctor',
      'None recorded': 'None recorded',
      'No Brands available': 'No Brands available',
      'No specific preparation needed.': 'No specific preparation needed.',
      'No information provided.': 'No information provided.',
      'Unknown Test': 'Unknown Test',
      'Diagnostic': 'Diagnostic',
      
      // Dynamic Cloud Data Translations (English -> English mapping to prevent key misses)
      'Erbil': 'Erbil',
      'Suleimani': 'Suleimani',
      'Duhok': 'Duhok',
      'Kirkuk': 'Kirkuk',
      'All Cities': 'All Cities',
      'All Specialties': 'All Specialties',
      'Cardiologist': 'Cardiologist',
      'Dermatologist': 'Dermatologist',
      'Neurologist': 'Neurologist',
      'Pediatrician': 'Pediatrician',
      'Ophthalmologist': 'Ophthalmologist',
      
      // Auth
      'login': 'Login',
      'login_subtitle': 'Welcome back! Please enter your details.',
      'email': 'Email Address',
      'password': 'Password',
      'login_btn': 'Log In',
      'no_account': 'Don\'t have an account?',
      'register': 'Create Account',
      'register_subtitle': 'Join us to manage your health.',
      'full_name': 'Full Name',
      'register_btn': 'Sign Up',
      'has_account': 'Already have an account?',
      'Orthopedic Surgeon': 'Orthopedic Surgeon',
      'Psychologist': 'Psychologist',
      'Dentist': 'Dentist',
      'Oncologist': 'Oncologist',
      'Radiologist': 'Radiologist',
      'Urologist': 'Urologist',
      'Gastroenterologist': 'Gastroenterologist',
      'ENT Specialist': 'ENT Specialist',
      'Endocrinologist': 'Endocrinologist',
      'Gynecologist': 'Gynecologist',
      'Specialty Unknown': 'Specialty Unknown',

      // Medical mock data fallback translations for En mode
      'Take 500mg-1g every 6 hours as needed.': 'Take 500mg-1g every 6 hours as needed.',
      'Complete the entire course without stopping.': 'Complete the entire course without stopping.',
      'Take with food to minimize stomach side effects.': 'Take with food to minimize stomach side effects.',
      'Take once daily at the same time.': 'Take once daily at the same time.',
      'Take 30 minutes before your first meal.': 'Take 30 minutes before your first meal.',
      
      'Liver damage if taken in extreme doses.': 'Liver damage if taken in extreme doses.',
      'Diarrhea, Nausea, Rash.': 'Diarrhea, Nausea, Rash.',
      'Stomach upset, metallic taste in mouth.': 'Stomach upset, metallic taste in mouth.',
      'Muscle pain, joint pain.': 'Muscle pain, joint pain.',
      'Headache, Abdominal pain.': 'Headache, Abdominal pain.',
      'Dry cough, dizziness.': 'Dry cough, dizziness.',

      'Blood Test': 'Blood Test',
      'Imaging': 'Imaging',

      'Blood will be drawn from your arm; expect a small pinch.': 'Blood will be drawn from your arm; expect a small pinch.',
      'Measures cholesterol levels to check heart health.': 'Measures cholesterol levels to check heart health.',
      'Gel is applied to the abdomen; uses sound waves to see organs.': 'Gel is applied to the abdomen; uses sound waves to see organs.',
      'Short exposure to radiation to image lungs and heart.': 'Short exposure to radiation to image lungs and heart.',
      'Standard blood draw for diabetes monitoring.': 'Standard blood draw for diabetes monitoring.',

      'No fasting required': 'No fasting required',
      'You can eat and drink normally': 'You can eat and drink normally',
      'Fasting 9-12 hours before test is Mandatory': 'Fasting 9-12 hours before test is Mandatory',
      'Fast for 8 hours': 'Fast for 8 hours',
      'Drink water as directed by technician': 'Drink water as directed by technician',
      'Remove jewelry and glasses': 'Remove jewelry and glasses',
      'Wear a clinical gown': 'Wear a clinical gown',
      'Shows average blood sugar for 3 months': 'Shows average blood sugar for 3 months',
    },
    'ku': {
      'app_title': 'تەندروستی',
      'directory': 'پزیشکەکان',
      'medicines': 'دەرمانەکان',
      'lab_guide': 'ڕێبەری پشکنین',
      'reminders': 'بیرخەرەوەکان',
      'settings': 'ڕێکخستنەکان',
      'city_filter': 'هەموو شارەکان',
      'admin_upload': 'بەڕێوەبەر: بارکردنی داتای سەرەتایی',
      'report_error': 'ڕاپۆرتکردنی هەڵە',
      'language': 'زمان',
      'kurdish': 'کوردی (سۆرانی)',
      'english': 'ئینگلیزی',
      'theme': 'دۆخی تاریک',
      'working_hours': 'کاتەکانی کارکردن:',
      'phone': 'تەلەفۆن:',
      'location': 'شوێن:',
      'usage': 'ڕێنماییەکانی بەکارهێنان',
      'side_effects': 'کاریگەرییە لاوەکییەکان',
      'specialty': 'پسپۆڕی:',
      'get_directions': 'رێنماییەکان وەربگرە',
      'empty_list': 'لیستی خاڵی. تکایە لە ڕێکخستنەکان داتای سەرەتایی باربکە.',
      'add_reminder': 'زیادکردنی بیرخەرەوە',
      'new_reminder': 'بیرخەرەوەی نوێ بۆ حەب',
      'medicine_name': 'ناوی دەرمان',
      'pick_time': 'کات هەڵبژێرە',
      'cancel': 'هەڵوەشاندنەوە',
      'schedule': 'دیاریکردنی کات',
      'save': 'هەڵگرتن',
      'add': 'زیادکردن',
      'dose_hint': 'بڕی دەرمان...',
      'no_reminders': 'هیچ بیرخەرەوەیەک دیارینەکراوە',
      'search_medicine': 'گەڕان بەپێی ناو یان مارکە',
      'search_doctor': 'گەڕان بەپێی ناو یان پسپۆڕی',
      'preparation': 'ئامادەکاری:',
      'what_to_expect': 'چی چاوەڕوان دەکرێت:',
      'no_tests': 'هیچ ڕێنماییەکی پشکنین لە کلۆوددا بەردەست نییە.',
      'app_preferences': 'هەڵبژاردەکانی ئەپ',
      'info_support': 'زانیاری و پاڵپشتی',
      'report_error_title': 'ڕاپۆرتکردنی هەڵە',
      'report_error_subtitle': 'ئاگادارکردنەوە لە ناونیشانی هەڵە',
      'seed_starting': 'بارکردنی داتا دەستی پێکرد...',
      'seed_success': 'هەموو داتاکان بە سەرکەوتوویی بۆ گۆگڵ بارکران!',
      'dark_mode': 'دۆخی تاریک',
      'dark_mode_sub': 'گۆڕینی ڕەنگی ئەپ',
      'currently': 'ئێستا:',
      'seed_subtitle': 'ناردنی هەموو داتاکان بۆ فایەربەیس',
      'notification_title': 'ئەوقاتی دەرمانەکەتە!',
      'notification_body': 'بیرخەرەوەی خۆشەویستانە بۆ خواردنی',
      'scheduled_dose': 'پشکی دیاریکراو',
      'email_subject': 'ڕاپۆرتی هەڵەی شوێنی کلینیک',
      'email_error': 'نەتوانرا ئەپی ئیمەیڵ بکرێتەوە',
      'app_subtitle': 'هاوڕێی تەندروستیت لە کوردستان',
      'directory_title': 'پزیشکەکان',
      'open': 'کراوەیە',
      'closed': 'داخراوە',
      'back': 'گەڕانەوە',
      'clinic_info': 'زانیاری کلینیک',
      'address': 'ناونیشان',
      'call_btn': 'پەیوەندیکردن',
      'report_incorrect': 'ڕاپۆرتکردنی زانیاری هەڵە',
      'my_doctors': 'پزیشکە دڵخوازەکانم',
      'saved': 'پاشەکەوتکراوە',
      'no_saved_doctors': 'پزیشکی زیاتر لە دایریکتۆرییەوە پاشەکەوت بکە',
      'saved_doctors': 'پزیشکی پاشەکەوتکراو',
      'my_medicines': 'دەرمانەکانم',
      'no_saved_medicines': 'هیچ دەرمانێک پاشەکەوت نەکراوە',
      'medicine_guide': 'ڕێبەری دەرمانەکان',
      'scientific_brand_search': 'گەڕان بەپێی ناوی زانستی و مارکە',
      'search_medicine_hint': 'بۆ نموونە: ئەڕۆکسیم، پانادۆڵ...',
      'uses': 'بەکارهێنانەکان',
      'dosage_info': 'بڕی دەرمان (دۆز)',
      'contraindications': 'حاڵەتە نەگونجاوەکان',
      'lab_diagnostics': 'پشکنینەکان و تاقیگە',
      'prep_guides': 'ڕێنماییەکانی ئامادەکاری',
      'search_tests_hint': 'گەڕان بۆ پشکنینەکان...',
      'prep_steps_count': 'هەنگاوی ئامادەکاری',
      'what_is_it': 'ئەمە چییە؟',
      'prep_steps': 'هەنگاوەکانی ئامادەکاری',
      'pill_reminders': 'بیرخەرەوەی حەبەکان',
      'never_miss_dose': 'هیچ ژەمێک لەدەست مەدە',
      'alarm_time_to_take': 'کاتی خواردنی دەرمانەکەتە!',
      'alarm_took_medicine': 'دەرمانەکەم خواردەوە',
      'sponsored': 'سپۆنسەرکراو',
      
      // Medicine/Test detail fallback strings
      'Medicine': 'دەرمان',
      'Vitamin': 'ڤیتامین',
      'Supplement': 'تێکمڵکەر',
      'No usage data': 'زانیاری بەکارهێنان بەردەست نییە',
      'Refer to doctor': 'پەیوەندی بە پزیشکەوە بکە',
      'None recorded': 'هیچ تۆمار نەکراوە',
      'No Brands available': 'هیچ مارکەیەک بەردەست نییە',
      'No specific preparation needed.': 'هیچ ئامادەکارییەکی تایبەت پێویست نییە.',
      'No information provided.': 'هیچ زانیارییەک نەدراوە.',
      'Unknown Test': 'پشکنینی نەناسراو',
      'Diagnostic': 'پشکنینی',

      // Dynamic Cloud Data Translations (English -> Kurdish)
      'Erbil': 'هەولێر',
      'Suleimani': 'سلێمانی',
      'Duhok': 'دهۆک',
      'Kirkuk': 'کەرکوک',
      'All Cities': 'هەموو شارەکان',
      'All Specialties': 'هەموو پسپۆڕییەکان',
      'Cardiologist': 'پزیشکی دڵ',
      'Dermatologist': 'پزیشکی پێست',
      'Neurologist': 'پزیشکی دەمار',
      'Pediatrician': 'پزیشکی منداڵان',
      'Ophthalmologist': 'پزیشکی چاو',
      
      // Auth
      'login': 'چوونە ژوورەوە',
      'login_subtitle': 'بەخێربێیتەوە! تکایە زانیارییەکانت بنووسە.',
      'email': 'ئیمەیڵ پێناسە',
      'password': 'وشەی نهێنی',
      'login_btn': 'بڕۆ ژوورەوە',
      'no_account': 'هەژمارت نییە؟',
      'register': 'دروستکردنی هەژمار',
      'register_subtitle': 'پەیوەندیمان پێوە بکە بۆ بەڕێوەبردنی تەندروستیت.',
      'full_name': 'ناوی تەواو',
      'register_btn': 'خۆتۆمارکردن',
      'has_account': 'پێشتر هەژمارت هەیە؟',
      'Orthopedic Surgeon': 'نەشتەرگەری ئێسک و شکان',
      'Psychologist': 'پزیشکی دەروونی',
      'Dentist': 'پزیشکی ددان',
      'Oncologist': 'پزیشکی شێرپەنجە',
      'Radiologist': 'پزیشکی تیشک',
      'Urologist': 'پزیشکی گورچیلە و میزەڕۆ',
      'Gastroenterologist': 'پزیشکی گەدە و ڕیخۆڵە',
      'ENT Specialist': 'پزیشکی قوڕگ و لووت و گوێ',
      'Endocrinologist': 'پزیشکی ڕژێنەکان',
      'Gynecologist': 'پزیشکی ژنان و منداڵبوون',
      'Specialty Unknown': 'پسپۆڕی نەزانراوە',

      // Medical mock data fallback translations (English -> Kurdish)
      'Take 500mg-1g every 6 hours as needed.': '٥٠٠مگم نزیکەی ١گم هەموو ٦ کاتژمێرێک بەپێی پێویست وەربگرە.',
      'Take 500mg - 1g every 6 hours as needed.': '٥٠٠مگم نزیکەی ١گم هەموو ٦ کاتژمێرێک بەپێی پێویست وەربگرە.', // Handle variant
      'Complete the entire course without stopping.': 'تەواوی کۆرسەکە بەبێ وەستان تەواو بکە.',
      'Take with food to minimize stomach side effects.': 'لەگەڵ خواردن بیخۆ بۆ کەمکردنەوەی کاریگەرییە لاوەکییەکانی گەدە.',
      'Take once daily at the same time.': 'تەنها یەکجار لە ڕۆژێکدا لە هەمان کاتدا بیخۆ.',
      'Take 30 minutes before your first meal.': '٣٠ خولەک پێش یەکەم ژەم بیخۆ.',
      
      'Liver damage if taken in extreme doses.': 'زیان بە جگەر دەگەیەنێت ئەگەر بەرێژەیەکی زۆر بەکاربهێنرێت.',
      'Diarrhea, Nausea, Rash.': 'سکچوون، دڵتێکەڵهاتن، پەڵەی پێست.',
      'Stomach upset, metallic taste in mouth.': 'تێکچوونی گەدە، تامی ئاسن لە دەمدا.',
      'Muscle pain, joint pain.': 'ئازاری ماسولکە، ئازاری جومگە.',
      'Headache, Abdominal pain.': 'سەرئێشە، ئازاری سک.',
      'Dry cough, dizziness.': 'کۆکەی وشک، سەرگێژخواردن.',

      'Blood Test': 'پشکنینی خوێن',
      'Imaging': 'وێنەگرتن',

      'Blood will be drawn from your arm; expect a small pinch.': 'خوێن لە قۆڵت وەردەگیرێت، پێشبینی کەمێک ئازار بکە.',
      'Measures cholesterol levels to check heart health.': 'ئاستی کۆلیسترۆڵ دەپێوێت بۆ پشکنینی تەندروستی دڵ.',
      'Gel is applied to the abdomen; uses sound waves to see organs.': 'جێڵ دەدرێت لە سک؛ شەپۆلی دەنگ بەکاردەهێنێت بۆ بینینی ئەندامەکان.',
      'Short exposure to radiation to image lungs and heart.': 'بەرکەوتنی کورت بە تیشک بۆ وێنەگرتنی سییەکان و دڵ.',
      'Standard blood draw for diabetes monitoring.': 'وەرگرتنی خوێنی ئاسایی بۆ چاودێریکردنی نەخۆشی شەکرە.',

      'No fasting required': 'پێویست بە بەرۆژووبوون ناکات',
      'You can eat and drink normally': 'دەتوانیت بە شێوەیەکی ئاسایی نان و ئاو بخۆیت',
      'Fasting 9-12 hours before test is Mandatory': 'بەرۆژووبوون بۆ ماوەی ٩-١٢ کاتژمێر پێش پشکنین زۆر پێویستە',
      'Fast for 8 hours': 'بۆ ماوەی ٨ کاتژمێر بەرۆژووبە',
      'Drink water as directed by technician': 'ئاو بخۆرەوە وەک ئەوەی لەلایەن شارەزایەکەوە پێڕاگەیندراوە',
      'Remove jewelry and glasses': 'زێڕ و چاویلکە دابنێ',
      'Wear a clinical gown': 'کەوای پزیشکی لەبەر بکە',
      'Shows average blood sugar for 3 months': 'ڕێژەی مامناوەندی شەکری خوێن بۆ ماوەی ٣ مانگ نیشان دەدات',
    },
  };

  static String translate(String key, String language) {
    String langCode = language == 'Kurdish' ? 'ku' : 'en';
    return _localizedValues[langCode]?[key] ?? key;
  }
}
