import '../models/doctor_model.dart';
import '../models/medicine_model.dart';
import '../models/medical_test_model.dart';

class MockDataService {
  static List<Doctor> getMockDoctors() {
    return [
      Doctor(
        id: 'd1',
        name: 'Dr. Alan Kurdi',
        specialty: 'Cardiologist',
        city: 'Erbil',
        phoneNumber: '+964 750 111 2222',
        clinicLocation: '100 Meter Road, Near Erbil International Hotel',
        latitude: 36.191,
        longitude: 43.993,
        workingHours: '4:00 PM - 8:00 PM',
        rating: 4.8,
      ),
      Doctor(
        id: 'd2',
        name: 'Dr. Nazira Ahmed',
        specialty: 'Dermatologist',
        city: 'Suleimani',
        phoneNumber: '+964 770 333 4444',
        clinicLocation: 'Salim Street, Near Faruk Mall',
        latitude: 35.556,
        longitude: 45.432,
        workingHours: '3:00 PM - 7:00 PM',
        rating: 4.9,
      ),
      Doctor(
        id: 'd3',
        name: 'Dr. Haval Darbandi',
        specialty: 'Neurologist',
        city: 'Duhok',
        phoneNumber: '+964 750 555 6666',
        clinicLocation: 'KRO Street, Near Duhok Main Bazaar',
        latitude: 36.862,
        longitude: 42.991,
        workingHours: '2:00 PM - 6:00 PM',
        rating: 4.6,
      ),
      Doctor(
        id: 'd4',
        name: 'Dr. Omer Salih',
        specialty: 'Pediatrician',
        city: 'Kirkuk',
        phoneNumber: '+964 771 111 4444',
        clinicLocation: 'Baghdad Road, Near Railway Station',
        latitude: 35.467,
        longitude: 44.393,
        workingHours: '9:00 AM - 1:00 PM',
        rating: 4.7,
      ),
      Doctor(
        id: 'd5',
        name: 'Dr. Sara Bakir',
        specialty: 'Ophthalmologist',
        city: 'Erbil',
        phoneNumber: '+964 750 888 9999',
        clinicLocation: '60 Meter Road, Gulan Street',
        latitude: 36.204,
        longitude: 44.009,
        workingHours: '10:00 AM - 3:00 PM',
        rating: 4.9,
      ),
      Doctor(
        id: 'd6',
        name: 'Dr. Hiwa Jalal',
        specialty: 'Orthopedic Surgeon',
        city: 'Suleimani',
        phoneNumber: '+964 770 112 3344',
        clinicLocation: 'Malikan Street, Slemani',
        latitude: 35.565,
        longitude: 45.421,
        workingHours: '4:00 PM - 9:00 PM',
        rating: 4.5,
      ),
      Doctor(
        id: 'd7',
        name: 'Dr. Zanko Amin',
        specialty: 'Psychologist',
        city: 'Duhok',
        phoneNumber: '+964 750 221 4455',
        clinicLocation: 'Shakhke Road, Duhok',
        latitude: 36.855,
        longitude: 43.003,
        workingHours: '11:00 AM - 5:00 PM',
        rating: 4.8,
      ),
      Doctor(
        id: 'd8',
        name: 'Dr. Lana Fatih',
        specialty: 'Dentist',
        city: 'Kirkuk',
        phoneNumber: '+964 771 223 5566',
        clinicLocation: 'Rahimawa Road, Kirkuk',
        latitude: 35.488,
        longitude: 44.401,
        workingHours: '3:00 PM - 8:00 PM',
        rating: 4.7,
      ),
      Doctor(
        id: 'd9',
        name: 'Dr. Karwan Karim',
        specialty: 'Oncologist',
        city: 'Erbil',
        phoneNumber: '+964 750 443 6677',
        clinicLocation: 'Ankawa Road, Near Ankawa Mall',
        latitude: 36.230,
        longitude: 43.995,
        workingHours: '1:00 PM - 6:00 PM',
        rating: 5.0,
      ),
      Doctor(
        id: 'd10',
        name: 'Dr. Shadi Mustafa',
        specialty: 'Radiologist',
        city: 'Suleimani',
        phoneNumber: '+964 770 556 7788',
        clinicLocation: 'Bakhtiary Street, Slemani',
        latitude: 35.545,
        longitude: 45.412,
        workingHours: '8:00 AM - 2:00 PM',
        rating: 4.6,
      ),
      Doctor(
        id: 'd11',
        name: 'Dr. Diyari Rasul',
        specialty: 'Urologist',
        city: 'Erbil',
        phoneNumber: '+964 750 667 8899',
        clinicLocation: 'Bakhtiary Quarter, Erbil',
        latitude: 36.208,
        longitude: 43.985,
        workingHours: '4:00 PM - 8:30 PM',
        rating: 4.7,
      ),
      Doctor(
        id: 'd12',
        name: 'Dr. Niza Osman',
        specialty: 'Gastroenterologist',
        city: 'Suleimani',
        phoneNumber: '+964 770 889 0011',
        clinicLocation: 'Kawa Street, Suleimani',
        latitude: 35.560,
        longitude: 45.445,
        workingHours: '3:30 PM - 7:30 PM',
        rating: 4.8,
      ),
      Doctor(
        id: 'd13',
        name: 'Dr. Baran Sidqi',
        specialty: 'ENT Specialist',
        city: 'Duhok',
        phoneNumber: '+964 750 990 1122',
        clinicLocation: 'Barzani Road, Duhok',
        latitude: 36.868,
        longitude: 42.985,
        workingHours: '4:00 PM - 8:00 PM',
        rating: 4.9,
      ),
       Doctor(
        id: 'd14',
        name: 'Dr. Rawand Azad',
        specialty: 'Endocrinologist',
        city: 'Erbil',
        phoneNumber: '+964 750 321 0000',
        clinicLocation: 'Dream City Med-Center',
        latitude: 36.220,
        longitude: 43.978,
        workingHours: '9:00 AM - 2:00 PM',
        rating: 4.5,
      ),
       Doctor(
        id: 'd15',
        name: 'Dr. Taban Ismael',
        specialty: 'Gynecologist',
        city: 'Kirkuk',
        phoneNumber: '+964 771 556 8899',
        clinicLocation: 'Nasr Street, Kirkuk',
        latitude: 35.465,
        longitude: 44.385,
        workingHours: '10:00 AM - 4:00 PM',
        rating: 4.8,
      ),
    ];
  }

  static List<Medicine> getMockMedicines() {
    return [
      Medicine(
        id: 'm1',
        scientificName: 'Paracetamol',
        commonBrands: ['Panadol', 'Tylenol', 'Adol'],
        indications: 'Mild to moderate pain, fever reduction.',
        sideEffects: 'Liver damage if taken in extreme doses.',
        usageInstructions: 'Take 500mg-1g every 6 hours as needed.',
      ),
      Medicine(
        id: 'm2',
        scientificName: 'Amoxicillin',
        commonBrands: ['Amoxil', 'Clamoxyl'],
        indications: 'Bacterial infections (throat, skin, chest).',
        sideEffects: 'Diarrhea, Nausea, Rash.',
        usageInstructions: 'Complete the entire course without stopping.',
      ),
      Medicine(
        id: 'm3',
        scientificName: 'Metformin',
        commonBrands: ['Glucophage', 'Glecomet'],
        indications: 'Type 2 Diabetes management.',
        sideEffects: 'Stomach upset, metallic taste in mouth.',
        usageInstructions: 'Take with food to minimize stomach side effects.',
      ),
      Medicine(
        id: 'm4',
        scientificName: 'Atorvastatin',
        commonBrands: ['Lipitor'],
        indications: 'High cholesterol and heart disease prevention.',
        sideEffects: 'Muscle pain, joint pain.',
        usageInstructions: 'Take once daily at the same time.',
      ),
      Medicine(
        id: 'm5',
        scientificName: 'Omeprazole',
        commonBrands: ['Prilosec', 'Losec'],
        indications: 'Acid reflux, GERD, and stomach ulcers.',
        sideEffects: 'Headache, Abdominal pain.',
        usageInstructions: 'Take 30 minutes before your first meal.',
      ),
      Medicine(
        id: 'm6',
        scientificName: 'Lisinopril',
        commonBrands: ['Zestril', 'Prinivil'],
        indications: 'High blood pressure and heart failure.',
        sideEffects: 'Dry cough, dizziness.',
        usageInstructions: 'Take once daily at the same time.',
      ),
    ];
  }

  static List<MedicalTest> getMockTests() {
    return [
      MedicalTest(
        id: 't1',
        testName: 'Complete Blood Count (CBC)',
        category: 'Blood Test',
        preparationInstruction: 'No fasting required. You can eat and drink normally.',
        whatToExpect: 'Blood will be drawn from your arm; expect a small pinch.',
      ),
      MedicalTest(
        id: 't2',
        testName: 'Lipid Panel',
        category: 'Blood Test',
        preparationInstruction: 'Fasting 9-12 hours before test is Mandatory.',
        whatToExpect: 'Measures cholesterol levels to check heart health.',
      ),
      MedicalTest(
        id: 't3',
        testName: 'Abdominal Ultrasound',
        category: 'Imaging',
        preparationInstruction: 'Fast for 8 hours. Drink water as directed by technician.',
        whatToExpect: 'Gel is applied to the abdomen; uses sound waves to see organs.',
      ),
      MedicalTest(
        id: 't4',
        testName: 'Chest X-Ray',
        category: 'Imaging',
        preparationInstruction: 'Remove jewelry and glasses. Wear a clinical gown.',
        whatToExpect: 'Short exposure to radiation to image lungs and heart.',
      ),
      MedicalTest(
        id: 't5',
        testName: 'HBA1C test',
        category: 'Blood Test',
        preparationInstruction: 'No fasting required. Shows average blood sugar for 3 months.',
        whatToExpect: 'Standard blood draw for diabetes monitoring.',
      ),
    ];
  }
}
