// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEx561bTve6q99qV-D9FeOma5cFEDrPoQ',
    appId: '1:878321739997:android:8958cb1d846f4c4a35d334',
    messagingSenderId: '878321739997',
    projectId: 'ttandrusti-3bacf',
    storageBucket: 'ttandrusti-3bacf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWxs03o--o7I97lk0C79cA1Xa4mqkmaaU',
    appId: '1:878321739997:ios:a74535c60ec408db35d334',
    messagingSenderId: '878321739997',
    projectId: 'ttandrusti-3bacf',
    storageBucket: 'ttandrusti-3bacf.firebasestorage.app',
    iosBundleId: 'com.example.tandrustiApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZC_OT0fTxjpn9w-k_5vX1ifTXp3C-V4',
    appId: '1:878321739997:web:e31eff9ee9939ddb35d334',
    messagingSenderId: '878321739997',
    projectId: 'ttandrusti-3bacf',
    authDomain: 'ttandrusti-3bacf.firebaseapp.com',
    storageBucket: 'ttandrusti-3bacf.firebasestorage.app',
    measurementId: 'G-6TKQR3FH0F',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ZC_OT0fTxjpn9w-k_5vX1ifTXp3C-V4',
    appId: '1:878321739997:web:a20fe393913be13f35d334',
    messagingSenderId: '878321739997',
    projectId: 'ttandrusti-3bacf',
    authDomain: 'ttandrusti-3bacf.firebaseapp.com',
    storageBucket: 'ttandrusti-3bacf.firebasestorage.app',
    measurementId: 'G-14T1WD8NYN',
  );

}